name: Generate README

on:
    push:
        branches:
            - main # Run this action on pushes to the main branch
    workflow_dispatch: # Allow manual triggering of the workflow

jobs:
    generate-readme:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.8" # Specify the Python version

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  # Add any additional dependencies if your script requires them
                  pip install requests

            - name: Run README generation script
              run: python readme_gen.py

            - name: Commit changes
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git add .
                  git commit -m "Auto-update README files" || echo "No changes to commit"
                  git push
